name: mimic_cxr
channels:
  - conda-forge
dependencies:
  - cudnn=8
  - python=3.10
  - pandas>=1.4.1,<1.5
  - pytorch>=1.11,<1.12
  - scikit-learn>=1.3,<1.4
  - torchvision>=0.12,<0.13
  - pip
  - pip:
    - nvflare==2.4.0
    - tensorboardX==2.6.2
